[project]
name = "puc-nsql-trabalho-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.5",
    "faker>=37.4.0",
    "loguru>=0.7.3",
    "pymysql>=1.1.1",
    "tqdm>=4.67.1",
]
